name: '[ Merge Master ] Build LA:T nginx and release file'
on:
  push:
    branches:
      - 'main'
jobs:
  centos7:
    name: ${{ github.job }}
    runs-on: ubuntu-latest
    steps:
      # check out repo
      - uses: actions/checkout@v2
      # setup JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # Build Install file
      - name: Build Open LA:T Web install file
        run: mvn -B package --file nginx-dist/pom.xml -Dcompile.os.name=${{ github.job }}
      - name: git config
        run: git config --global http.version HTTP/1.1
      - name: git config2
        run: git config --global http.postBuffer 157286400
      - name: Push test another repository in github engn(dmnemec)
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'nginx-dist/target/nginx/.'
          destination_repo: 'ATLENA/lat-engine'
          destination_folder: 'nginx'
          user_email: 'seosej@gmail.com '
          user_name: 'Sejin Seo'