name: '[ Merge Master ] Build LA:T nginx and release file'
on:
  push:
    branches:
      - 'main'
jobs:
  centos7:
    name: ${{ github.job }}
    runs-on: ubuntu-latest
    steps:
      # check out repo
      - uses: actions/checkout@v2
      # setup JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # Build Install file
      - name: Build Open LA:T Web install file
        run: mvn -B package --file nginx-dist/pom.xml -Dcompile.os.name=${{ github.job }}
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{ secrets.GIT_CREDENTIALS }}
      - name: git push
        run: |
          rm -rf /tmp/nginx-test
          mkdir -p /tmp/nginx-test
          git clone https://github.com/ATLENA/lat-engine.git /tmp/nginx-temp
          git config --global user.email "seosej@gmail.com"
          git config --global user.name "seosej"
          ls -al /tmp/nginx-temp
          cp -rf nginx-dist/target/nginx/* /tmp/nginx-temp/nginx/      
          cd /tmp/nginx-temp && git add . && git commit -a -m "Pushed from lat-nginx" && git push
