name: '[ Merge Master ] Build LA:T nginx and release file'
on:
  push:
    branches:
      - 'main'
jobs:
  centos7:
    name: ${{ github.job }}
    runs-on: ubuntu-latest
    steps:
      # check out repo
      - uses: actions/checkout@v2
      # setup JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # Build Install file
      - name: Build Open LA:T Web install file
        run: mvn -B package --file nginx-dist/pom.xml -Dcompile.os.name=${{ github.job }}
      - name: git clone
        run: |
          rm -rf /tmp/nginx-test
          mkdir -p /tmp/nginx-test
          git clone https://github.com/ATLENA/lat-engine.git /tmp/nginx-test
          ls -al /tmp/nginx-test
          cp -rf nginx-dist/target/nginx/* /tmp/nginx-test/nginx/
          git config --global user.email "seosej@gmail.com"
          git config --global user.name "Sejin Seo"
          echo "https://seosej@gmail.com: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@github.com" > ~/.git-credentials
          cd /tmp/nginx-test && git add . && git commit -a -m "test" && git push
